### ISSUE TITLE
System.Exception: 'Unknown SQL Datatype: Byte'

### ISSUE THREAD

**Issue by boydlee** [oeoren/ApirIO#8]
When running the project, the code fails to build and throws the following exception in **APiAssemblyResolver.cs:**

```
System.Exception
  HResult=0x80131500
  Message=Unknown SQL Datatype: Byte
  Source=NTIAPI
  StackTrace:
   at NTIAPI.App_Start.ApirAssemblyResolver.GetAssemblies() in C:\Users\nti\source\repos\NTIAPI\App_Start\ApirAssemblyResolver.cs:line 40
   at System.Web.Http.Dispatcher.DefaultHttpControllerTypeResolver.GetControllerTypes(IAssembliesResolver assembliesResolver)
   at System.Web.Http.WebHost.WebHostHttpControllerTypeResolver.GetControllerTypes(IAssembliesResolver assembliesResolver)
   at System.Web.Http.Dispatcher.HttpControllerTypeCache.InitializeCache()
   at System.Lazy`1.CreateValue()
```

I believe that it might be down to usage of the SQL column type **'TinyInt'** which doesn't seem to be mapped in **TypeMapper.cs.** Any chance of a fix and updated package?

The table structure in question looks like: 

```
[dbo].[cms6_Content](
	[ContentID] [int] IDENTITY(150,1) NOT NULL,
	[ContentName] [varchar](100) NULL,
	[PageTitle] [varchar](100) NULL,
	[PageDescription] [varchar](240) NULL,
	[PageKeywords] [varchar](180) NULL,
	[PageContent] [ntext] NULL,
	[GroupPermissions] [smallint] NULL,
	[SiteID] [smallint] NULL,
	[ContentTypeID] [int] NULL,
	[DateAdded] [datetime] NULL,
	[HeaderID] [int] NULL,
	[RHmenuID] [int] NULL,
	[RHmenu2ID] [int] NULL,
	[RHmenu3ID] [int] NULL,
	[LHmenuID] [int] NULL,
	[LHmenu2ID] [int] NULL,
	[LHmenu3ID] [int] NULL,
	[FooterID] [int] NULL,
	[SubnavID] [int] NULL,
	[Subnav2ID] [int] NULL,
	[URLoptimize] [varchar](350) NULL,
	[ContentDateModified] [datetime] NULL,
	[Util_01] [varchar](50) NULL,
	[Util_02] [varchar](50) NULL,
	[Util_03] [varchar](50) NULL,
	[Util_04] [varchar](50) NULL,
	[Util_05] [varchar](50) NULL,
	[Util_06] [varchar](50) NULL,
	[Util_07] [varchar](50) NULL,
	[Util_08] [varchar](50) NULL,
	[Util_09] [varchar](50) NULL,
	[MenuWidth] [int] NULL,
	[NewsThumb] [varchar](100) NULL,
	[Picasa] [varchar](250) NULL,
	[Tags] [varchar](1000) NULL,
	[TagsOperator] [tinyint] NULL,
	[IncludeNews] [bit] NULL,
	[IncludeNotice] [bit] NULL,
	[IsCategory] [bit] NULL,
	[ParentCategory] [int] NULL,
	[ParentPage] [int] NULL,
	[ParentPageLast] [int] NULL,
	[ParentPageLast1] [int] NULL,
	[VideoUrl] [varchar](100) NULL,
	[Comments] [tinyint] NULL,
	[CommentsCount] [int] NULL,
	[HasGallery] [tinyint] NULL,
	[ContentOrder] [int] NULL,
	[ExtraStyles] [varchar](max) NULL,
	[Redirect] [varchar](200) NULL,
	[Activate] [tinyint] NULL,
	[ExpiryDate] [datetime] NULL,
	[UrlName] [varchar](100) NULL,
	[URLoptimize2] [varchar](350) NULL,
	[RunFile] [varchar](50) NULL,
	[PostIsListing] [tinyint] NULL,
	[AllowedGroups] [varchar](150) NULL,
	[RHmenu4ID] [int] NULL,
	[RHmenu5ID] [int] NULL,
	[RHmenu6ID] [int] NULL,
	[DctFld] [varchar](max) NULL,
	[AdminID] [int] NULL,
 

```

**Comment by oeoren** [comment]
You are right, the library does not know about tinyInt. I will fix that in the next release.
In the mean time could you just cast it to an int in the get procedure

**Comment by boydlee** [comment]
Thanks, can confirm CAST as int gets around the issue. Appreciate the quick reply
